  
# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT project.wsgi

beta_settings:
    cloud_sql_instances: vircom:us-central1:vircom-instance

runtime_config:
  python_version: 3
# [END runtime]